[package]
name = "tagger"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
once_cell = "1.20.3"
serde = { version = "1.0.218", features = ["derive"] }
serde_yaml = "0.9.34"
walkdir = "2.5.0"
